name: productivity_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_storage: ^11.7.1
  cloud_firestore: ^4.16.1
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  uuid: ^4.4.0
  intl: ^0.19.0
  numberpicker: ^2.1.2
  table_calendar: ^3.1.1
  swipe_to: ^1.0.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

